stages:
   - lint
   - image
   - test
   - demo
   - release

default:
   tags:
      - docker

variables:
   CONTAINER_COMMIT_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
   CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
   CI_RUNNER_ARCHITECTURE: amd64

# jobs

flake8:
   stage: lint
   image: pipelinecomponents/flake8:latest
   script:
      - flake8 --verbose .

.image build:
   stage: image
   image: docker:latest
   variables:
      PLATFORMS: linux/$CI_RUNNER_ARCHITECTURE
      ARCH: $CI_RUNNER_ARCHITECTURE
   script:
      - echo CONTAINER_COMMIT_IMAGE = "$CONTAINER_COMMIT_IMAGE"
      - echo CONTAINER_LATEST_IMAGE = "$CONTAINER_LATEST_IMAGE"
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker buildx create 
               --driver=docker-container 
               --name=multi 
               --platform="$PLATFORMS"
               --bootstrap
      - docker buildx build
               --build-arg="BUILDKIT_INLINE_CACHE=1"
               --build-arg="DOLFINY_BUILD_TYPE=RelWithDebInfo"
               --cache-from="$CONTAINER_COMMIT_IMAGE-$ARCH"
               --cache-from="$CONTAINER_LATEST_IMAGE-$ARCH"
               --tag="$CONTAINER_COMMIT_IMAGE-$ARCH"
               --pull
               --load
               --builder=multi --platform="$PLATFORMS"
               .
      - docker push "$CONTAINER_COMMIT_IMAGE-$ARCH"

image build amd64:
   extends: .image build
   variables:
      PLATFORMS: linux/amd64
      ARCH: amd64

image build arm64:
   extends: .image build
   variables:
      PLATFORMS: linux/arm64
      ARCH: arm64
   rules:
      - if: ($CI_COMMIT_BRANCH == "master" || $CI_PIPELINE_SOURCE == "schedule")
      - exists: 
         - Dockerfile
        when: manual
        allow_failure: true

image release:
   stage: release
   image: docker:latest
   script:
      - echo "Gitlab registry -- login, tag, manifest and push"
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker pull $CONTAINER_COMMIT_IMAGE-amd64
      - docker pull $CONTAINER_COMMIT_IMAGE-arm64
      - docker manifest create $CONTAINER_COMMIT_IMAGE $CONTAINER_COMMIT_IMAGE-amd64 $CONTAINER_COMMIT_IMAGE-arm64
      - docker manifest push $CONTAINER_COMMIT_IMAGE
      - docker manifest create $CONTAINER_LATEST_IMAGE $CONTAINER_COMMIT_IMAGE-amd64 $CONTAINER_COMMIT_IMAGE-arm64
      - docker manifest push $CONTAINER_LATEST_IMAGE
      - echo "DockerHub registry -- login, tag, manifest and push"
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - docker tag $CONTAINER_COMMIT_IMAGE-amd64 $DOCKERHUB_COMMIT_IMAGE-amd64
      - docker tag $CONTAINER_COMMIT_IMAGE-arm64 $DOCKERHUB_COMMIT_IMAGE-arm64
      - docker push $DOCKERHUB_COMMIT_IMAGE-amd64
      - docker push $DOCKERHUB_COMMIT_IMAGE-arm64
      - docker manifest create $DOCKERHUB_COMMIT_IMAGE $DOCKERHUB_COMMIT_IMAGE-amd64 $DOCKERHUB_COMMIT_IMAGE-arm64
      - docker manifest push $DOCKERHUB_COMMIT_IMAGE
      - echo "DockerHub registry -- pull and test"
      - docker image ls $DOCKERHUB_COMMIT_IMAGE -aq | xargs docker rmi -f
      - docker pull $DOCKERHUB_COMMIT_IMAGE
      - docker image ls $DOCKERHUB_COMMIT_IMAGE --no-trunc
      - docker run --platform linux/amd64 $DOCKERHUB_COMMIT_IMAGE uname -m > amd64.txt
      - grep -q "x86_64" amd64.txt
      - docker run --platform linux/arm64 $DOCKERHUB_COMMIT_IMAGE uname -m > arm64.txt
      - grep -q "aarch64" arm64.txt
   rules:
      - if: ($CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "master")
        variables:
           DOCKERHUB_COMMIT_IMAGE: dolfiny/dolfiny:nightly
      - if: ($CI_COMMIT_BRANCH == "master")
        variables:
           DOCKERHUB_COMMIT_IMAGE: dolfiny/dolfiny:latest

.test_template:
   stage: test
   image: $CONTAINER_COMMIT_IMAGE-$CI_RUNNER_ARCHITECTURE
   before_script:
      - pip3 install .
      - cd test
   artifacts:
      name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-artifacts"
      paths:
         - test/*/*
      expire_in: 1 week

test/unit/serial:
   extends: .test_template
   script:
      - cd unit
      - python3 -u -m pytest -n 8 -vsx .

test/unit/parallel:
   extends: .test_template
   script:
      - cd unit
      - mpirun -n 2 python3 -u -m pytest -vsx .

test/convergence:
   extends: .test_template
   script:
      - cd convergence
      - python3 -u -m pytest -n 8 -m 'convergence' -vsx .
      - python3 -u -m pytest -n 8 -m 'postprocess' -vsx .
   rules:
      - if: ($CI_RUN_TEST_CONVERGENCE == "yes")
      - if: ($CI_COMMIT_BRANCH)
        changes:
         - test/convergence/*.py
        when: always
      - exists: 
         - test/convergence/*.py
        when: manual
        allow_failure: true

.demo_template:
   stage: demo
   image: $CONTAINER_COMMIT_IMAGE-$CI_RUNNER_ARCHITECTURE
   before_script:
      - pip3 install .
      - cd demo
   rules:
      - if: ($CI_PIPELINE_SOURCE == "merge_request_event")
      - if: ($CI_PIPELINE_SOURCE == "schedule")
      - if: ($CI_COMMIT_BRANCH)
        changes:
         - demo/*/*
      - exists: 
         - demo/*/*.py
        when: manual
        allow_failure: true
   artifacts:
      name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-artifacts"
      paths:
         - demo/*/*
      expire_in: 1 week

demo/bingham:
   extends: .demo_template
   script:
      - cd bingham
      - mpirun -n 2 python3 bingham_block.py
      - mpirun -n 2 python3 bingham_lm_block.py

demo/beam:
   extends: .demo_template
   script:
      - cd beam
      - mpirun -n 2 python3 beam_curved_finitestrain_bstar.py
      - mpirun -n 1 python3 beam_curved_finitestrain_bstar.py
      - mpirun -n 2 python3 beam_curved_finitestrain_bzero.py
      - mpirun -n 1 python3 beam_curved_finitestrain_bzero.py

demo/vsolid:
   extends: .demo_template
   script:
      - cd vsolid
      - mpirun -n 2 python3 duffing.py
      - mpirun -n 4 python3 solid_disp_tda.py
      # - mpirun -n 4 python3 solid_dispstress_tda.py
      # - mpirun -n 4 python3 solid_velostress_tda.py

demo/plasticity:
   extends: .demo_template
   script:
      - cd plasticity 
      - mpirun -n 8 python3 solid_plasticity_monolithic.py

demo/plasticity_rankine:
   extends: .demo_template
   script:
      - cd plasticity_rankine
      - mpirun -n 8 python3 rankine.py

demo/spectral:
   extends: .demo_template
   script:
      - cd spectral 
      - mpirun -n 8 python3 spectral_elasticity.py

demo/continuation:
   extends: .demo_template
   script:
      - cd continuation
      - mpirun -n 1 python3 continuation_planartruss.py
      - mpirun -n 1 python3 continuation_planartruss_disp.py
